apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  namespace: project
  name: rate
spec:
  metrics:
  - name: rate
    initialDelay: 10m
    successCondition: result < 2
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1658-prometheus.prometheus.svc.cluster.local:9090
        query: |
          scalar(sum(rate(container_cpu_usage_seconds_total{namespace="project", container=~"project.*"}[8m])))
