apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: webserver
          image: PROJECT/IMAGE
          resources:
            limits:
              cpu: "250m"
              memory: "250Mi"
          volumeMounts:
          - name: shared-image
            mountPath: /usr/src/app/files
            subPath: app
            
